version: '3.8'

services:
  database:
    container_name: postgres-server
    restart: always
    image: postgres:latest
    volumes:
      - ./initilization/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=socialfood
    networks:
      - social-food-management-network

  server:
    container_name: golang-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - social-food-management-network

volumes:
  dbinit:
  golang-server:

networks:
  social-food-management-network:
    driver: bridge