// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account           string
	Destination       string
	DestinationDetail string
	DestinationRank   string
	Restaurant        string
	RestaurantDishes  string
	RestaurantPhotos  string
	RestaurantRank    string
	RestaurantReviews string
}{
	Account:           "account",
	Destination:       "destination",
	DestinationDetail: "destination_detail",
	DestinationRank:   "destination_rank",
	Restaurant:        "restaurant",
	RestaurantDishes:  "restaurant_dishes",
	RestaurantPhotos:  "restaurant_photos",
	RestaurantRank:    "restaurant_rank",
	RestaurantReviews: "restaurant_reviews",
}
