// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDestinationRanks(t *testing.T) {
	t.Parallel()

	query := DestinationRanks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDestinationRanksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDestinationRanksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DestinationRanks().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDestinationRanksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DestinationRankSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDestinationRanksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DestinationRankExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DestinationRank exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DestinationRankExists to return true, but got false.")
	}
}

func testDestinationRanksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	destinationRankFound, err := FindDestinationRank(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if destinationRankFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDestinationRanksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DestinationRanks().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDestinationRanksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DestinationRanks().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDestinationRanksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	destinationRankOne := &DestinationRank{}
	destinationRankTwo := &DestinationRank{}
	if err = randomize.Struct(seed, destinationRankOne, destinationRankDBTypes, false, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}
	if err = randomize.Struct(seed, destinationRankTwo, destinationRankDBTypes, false, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = destinationRankOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = destinationRankTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DestinationRanks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDestinationRanksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	destinationRankOne := &DestinationRank{}
	destinationRankTwo := &DestinationRank{}
	if err = randomize.Struct(seed, destinationRankOne, destinationRankDBTypes, false, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}
	if err = randomize.Struct(seed, destinationRankTwo, destinationRankDBTypes, false, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = destinationRankOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = destinationRankTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func destinationRankBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func destinationRankAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DestinationRank) error {
	*o = DestinationRank{}
	return nil
}

func testDestinationRanksHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DestinationRank{}
	o := &DestinationRank{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, destinationRankDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DestinationRank object: %s", err)
	}

	AddDestinationRankHook(boil.BeforeInsertHook, destinationRankBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	destinationRankBeforeInsertHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.AfterInsertHook, destinationRankAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	destinationRankAfterInsertHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.AfterSelectHook, destinationRankAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	destinationRankAfterSelectHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.BeforeUpdateHook, destinationRankBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	destinationRankBeforeUpdateHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.AfterUpdateHook, destinationRankAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	destinationRankAfterUpdateHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.BeforeDeleteHook, destinationRankBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	destinationRankBeforeDeleteHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.AfterDeleteHook, destinationRankAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	destinationRankAfterDeleteHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.BeforeUpsertHook, destinationRankBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	destinationRankBeforeUpsertHooks = []DestinationRankHook{}

	AddDestinationRankHook(boil.AfterUpsertHook, destinationRankAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	destinationRankAfterUpsertHooks = []DestinationRankHook{}
}

func testDestinationRanksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDestinationRanksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(destinationRankColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDestinationRankToOneDestinationUsingDestination(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local DestinationRank
	var foreign Destination

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, destinationRankDBTypes, false, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, destinationDBTypes, false, destinationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Destination struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.DestinationID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Destination().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := DestinationRankSlice{&local}
	if err = local.L.LoadDestination(ctx, tx, false, (*[]*DestinationRank)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Destination == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Destination = nil
	if err = local.L.LoadDestination(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Destination == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testDestinationRankToOneSetOpDestinationUsingDestination(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a DestinationRank
	var b, c Destination

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, destinationRankDBTypes, false, strmangle.SetComplement(destinationRankPrimaryKeyColumns, destinationRankColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, destinationDBTypes, false, strmangle.SetComplement(destinationPrimaryKeyColumns, destinationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, destinationDBTypes, false, strmangle.SetComplement(destinationPrimaryKeyColumns, destinationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Destination{&b, &c} {
		err = a.SetDestination(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Destination != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DestinationRanks[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.DestinationID != x.ID {
			t.Error("foreign key was wrong value", a.DestinationID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DestinationID))
		reflect.Indirect(reflect.ValueOf(&a.DestinationID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.DestinationID != x.ID {
			t.Error("foreign key was wrong value", a.DestinationID, x.ID)
		}
	}
}

func testDestinationRanksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDestinationRanksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DestinationRankSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDestinationRanksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DestinationRanks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	destinationRankDBTypes = map[string]string{`ID`: `integer`, `DestinationID`: `integer`, `Vote`: `double precision`, `TotalOfVote`: `integer`}
	_                      = bytes.MinRead
)

func testDestinationRanksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(destinationRankPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(destinationRankAllColumns) == len(destinationRankPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDestinationRanksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(destinationRankAllColumns) == len(destinationRankPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DestinationRank{}
	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, destinationRankDBTypes, true, destinationRankPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(destinationRankAllColumns, destinationRankPrimaryKeyColumns) {
		fields = destinationRankAllColumns
	} else {
		fields = strmangle.SetComplement(
			destinationRankAllColumns,
			destinationRankPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DestinationRankSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDestinationRanksUpsert(t *testing.T) {
	t.Parallel()

	if len(destinationRankAllColumns) == len(destinationRankPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DestinationRank{}
	if err = randomize.Struct(seed, &o, destinationRankDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DestinationRank: %s", err)
	}

	count, err := DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, destinationRankDBTypes, false, destinationRankPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DestinationRank struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DestinationRank: %s", err)
	}

	count, err = DestinationRanks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
