// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Destinations", testDestinationsUpsert)

	t.Run("DestinationDetails", testDestinationDetailsUpsert)

	t.Run("DestinationRanks", testDestinationRanksUpsert)

	t.Run("Restaurants", testRestaurantsUpsert)

	t.Run("RestaurantDishes", testRestaurantDishesUpsert)

	t.Run("RestaurantPhotos", testRestaurantPhotosUpsert)

	t.Run("RestaurantRanks", testRestaurantRanksUpsert)

	t.Run("RestaurantReviews", testRestaurantReviewsUpsert)
}
