// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRestaurantReviews(t *testing.T) {
	t.Parallel()

	query := RestaurantReviews()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRestaurantReviewsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRestaurantReviewsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RestaurantReviews().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRestaurantReviewsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RestaurantReviewSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRestaurantReviewsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RestaurantReviewExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RestaurantReview exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RestaurantReviewExists to return true, but got false.")
	}
}

func testRestaurantReviewsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	restaurantReviewFound, err := FindRestaurantReview(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if restaurantReviewFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRestaurantReviewsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RestaurantReviews().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRestaurantReviewsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RestaurantReviews().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRestaurantReviewsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	restaurantReviewOne := &RestaurantReview{}
	restaurantReviewTwo := &RestaurantReview{}
	if err = randomize.Struct(seed, restaurantReviewOne, restaurantReviewDBTypes, false, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}
	if err = randomize.Struct(seed, restaurantReviewTwo, restaurantReviewDBTypes, false, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = restaurantReviewOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = restaurantReviewTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RestaurantReviews().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRestaurantReviewsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	restaurantReviewOne := &RestaurantReview{}
	restaurantReviewTwo := &RestaurantReview{}
	if err = randomize.Struct(seed, restaurantReviewOne, restaurantReviewDBTypes, false, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}
	if err = randomize.Struct(seed, restaurantReviewTwo, restaurantReviewDBTypes, false, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = restaurantReviewOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = restaurantReviewTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func restaurantReviewBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func restaurantReviewAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *RestaurantReview) error {
	*o = RestaurantReview{}
	return nil
}

func testRestaurantReviewsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &RestaurantReview{}
	o := &RestaurantReview{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RestaurantReview object: %s", err)
	}

	AddRestaurantReviewHook(boil.BeforeInsertHook, restaurantReviewBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	restaurantReviewBeforeInsertHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.AfterInsertHook, restaurantReviewAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	restaurantReviewAfterInsertHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.AfterSelectHook, restaurantReviewAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	restaurantReviewAfterSelectHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.BeforeUpdateHook, restaurantReviewBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	restaurantReviewBeforeUpdateHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.AfterUpdateHook, restaurantReviewAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	restaurantReviewAfterUpdateHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.BeforeDeleteHook, restaurantReviewBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	restaurantReviewBeforeDeleteHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.AfterDeleteHook, restaurantReviewAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	restaurantReviewAfterDeleteHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.BeforeUpsertHook, restaurantReviewBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	restaurantReviewBeforeUpsertHooks = []RestaurantReviewHook{}

	AddRestaurantReviewHook(boil.AfterUpsertHook, restaurantReviewAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	restaurantReviewAfterUpsertHooks = []RestaurantReviewHook{}
}

func testRestaurantReviewsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRestaurantReviewsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(restaurantReviewColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRestaurantReviewToOneAccountUsingAccount(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local RestaurantReview
	var foreign Account

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, restaurantReviewDBTypes, false, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, accountDBTypes, false, accountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Account struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.AccountID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Account().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RestaurantReviewSlice{&local}
	if err = local.L.LoadAccount(ctx, tx, false, (*[]*RestaurantReview)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Account == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Account = nil
	if err = local.L.LoadAccount(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Account == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRestaurantReviewToOneRestaurantUsingRestaurant(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local RestaurantReview
	var foreign Restaurant

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, restaurantReviewDBTypes, false, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, restaurantDBTypes, false, restaurantColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Restaurant struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.RestaurantID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Restaurant().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RestaurantReviewSlice{&local}
	if err = local.L.LoadRestaurant(ctx, tx, false, (*[]*RestaurantReview)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Restaurant == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Restaurant = nil
	if err = local.L.LoadRestaurant(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Restaurant == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRestaurantReviewToOneSetOpAccountUsingAccount(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a RestaurantReview
	var b, c Account

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, restaurantReviewDBTypes, false, strmangle.SetComplement(restaurantReviewPrimaryKeyColumns, restaurantReviewColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Account{&b, &c} {
		err = a.SetAccount(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Account != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RestaurantReviews[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.AccountID != x.ID {
			t.Error("foreign key was wrong value", a.AccountID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AccountID))
		reflect.Indirect(reflect.ValueOf(&a.AccountID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.AccountID != x.ID {
			t.Error("foreign key was wrong value", a.AccountID, x.ID)
		}
	}
}
func testRestaurantReviewToOneSetOpRestaurantUsingRestaurant(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a RestaurantReview
	var b, c Restaurant

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, restaurantReviewDBTypes, false, strmangle.SetComplement(restaurantReviewPrimaryKeyColumns, restaurantReviewColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, restaurantDBTypes, false, strmangle.SetComplement(restaurantPrimaryKeyColumns, restaurantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, restaurantDBTypes, false, strmangle.SetComplement(restaurantPrimaryKeyColumns, restaurantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Restaurant{&b, &c} {
		err = a.SetRestaurant(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Restaurant != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.RestaurantReviews[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.RestaurantID != x.ID {
			t.Error("foreign key was wrong value", a.RestaurantID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.RestaurantID))
		reflect.Indirect(reflect.ValueOf(&a.RestaurantID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.RestaurantID != x.ID {
			t.Error("foreign key was wrong value", a.RestaurantID, x.ID)
		}
	}
}

func testRestaurantReviewsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRestaurantReviewsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RestaurantReviewSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRestaurantReviewsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RestaurantReviews().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	restaurantReviewDBTypes = map[string]string{`ID`: `integer`, `RestaurantID`: `integer`, `AccountID`: `integer`, `Rating`: `integer`, `Text`: `text`}
	_                       = bytes.MinRead
)

func testRestaurantReviewsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(restaurantReviewPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(restaurantReviewAllColumns) == len(restaurantReviewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRestaurantReviewsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(restaurantReviewAllColumns) == len(restaurantReviewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RestaurantReview{}
	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, restaurantReviewDBTypes, true, restaurantReviewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(restaurantReviewAllColumns, restaurantReviewPrimaryKeyColumns) {
		fields = restaurantReviewAllColumns
	} else {
		fields = strmangle.SetComplement(
			restaurantReviewAllColumns,
			restaurantReviewPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RestaurantReviewSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRestaurantReviewsUpsert(t *testing.T) {
	t.Parallel()

	if len(restaurantReviewAllColumns) == len(restaurantReviewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RestaurantReview{}
	if err = randomize.Struct(seed, &o, restaurantReviewDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RestaurantReview: %s", err)
	}

	count, err := RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, restaurantReviewDBTypes, false, restaurantReviewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RestaurantReview struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RestaurantReview: %s", err)
	}

	count, err = RestaurantReviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
